// <auto-generated />
using System;
using CleanArchitectureCQRs.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CleanArchitectureCQRs.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241121150728_last")]
    partial class last
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CleanArchitectureCQRs.Domain.Entites.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6a8e0860-4e87-4965-a821-1ac325858abb"),
                            Description = "Devices and gadgets",
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = new Guid("e3a694e6-fa54-41dc-b740-3c6afdfa06ea"),
                            Description = "Various genres of books",
                            Name = "Books"
                        },
                        new
                        {
                            Id = new Guid("86a839c3-816a-463b-b639-28c4e1fa207f"),
                            Description = "Apparel for men and women",
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = new Guid("778e533a-cd4f-431c-a1f8-96ff9e515ce1"),
                            Description = "Household items",
                            Name = "Home & Kitchen"
                        },
                        new
                        {
                            Id = new Guid("7eb666f0-9b4d-4c80-a936-104e851f745a"),
                            Description = "Sporting goods and equipment",
                            Name = "Sports"
                        },
                        new
                        {
                            Id = new Guid("96491df2-8f2b-483a-b709-6af695179444"),
                            Description = "Toys for children of all ages",
                            Name = "Toys"
                        },
                        new
                        {
                            Id = new Guid("5fa83ce1-299b-4c82-a4c5-99916f7629fd"),
                            Description = "Healthcare and beauty products",
                            Name = "Health & Beauty"
                        },
                        new
                        {
                            Id = new Guid("7f164413-279c-44a4-9e7c-0967d20aa4d4"),
                            Description = "Car parts and accessories",
                            Name = "Automotive"
                        },
                        new
                        {
                            Id = new Guid("eb97dc31-843c-4f28-922d-48520a790717"),
                            Description = "Instruments and music equipment",
                            Name = "Music"
                        },
                        new
                        {
                            Id = new Guid("d16b79f3-e17e-45b5-a911-0fd3e9818485"),
                            Description = "Stationery and office essentials",
                            Name = "Office Supplies"
                        });
                });

            modelBuilder.Entity("CleanArchitectureCQRs.Domain.Entites.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8b7ebfb0-7d4b-40ff-a911-c6ca2079e50e"),
                            CategoryId = new Guid("6a8e0860-4e87-4965-a821-1ac325858abb"),
                            Description = "Latest model",
                            Image = "smartphone.jpg",
                            Name = "Smartphone",
                            Price = 699
                        },
                        new
                        {
                            Id = new Guid("e40f993d-20c8-46a4-abe2-20d4e564726e"),
                            CategoryId = new Guid("6a8e0860-4e87-4965-a821-1ac325858abb"),
                            Description = "15-inch display",
                            Image = "laptop.jpg",
                            Name = "Laptop",
                            Price = 999
                        },
                        new
                        {
                            Id = new Guid("4ca4dcd5-1353-4782-9e5e-f07db5a854c3"),
                            CategoryId = new Guid("6a8e0860-4e87-4965-a821-1ac325858abb"),
                            Description = "Water-resistant smartwatch",
                            Image = "smartwatch.jpg",
                            Name = "Smartwatch",
                            Price = 199
                        },
                        new
                        {
                            Id = new Guid("abc6bcb1-3392-4d87-bb86-70216cbd45cb"),
                            CategoryId = new Guid("e3a694e6-fa54-41dc-b740-3c6afdfa06ea"),
                            Description = "Portable e-book reader",
                            Image = "ebook.jpg",
                            Name = "E-book Reader",
                            Price = 129
                        },
                        new
                        {
                            Id = new Guid("7e5cdc5c-16dd-4eae-b718-233021071b80"),
                            CategoryId = new Guid("e3a694e6-fa54-41dc-b740-3c6afdfa06ea"),
                            Description = "Bestselling novel",
                            Image = "book.jpg",
                            Name = "Fiction Book",
                            Price = 20
                        },
                        new
                        {
                            Id = new Guid("1eb11926-885f-4fcb-8740-b1a4a284c248"),
                            CategoryId = new Guid("e3a694e6-fa54-41dc-b740-3c6afdfa06ea"),
                            Description = "Self-improvement guide",
                            Image = "self_help.jpg",
                            Name = "Self-help Book",
                            Price = 15
                        },
                        new
                        {
                            Id = new Guid("70daa20c-83db-4be2-98a7-8af56bfc2ab0"),
                            CategoryId = new Guid("86a839c3-816a-463b-b639-28c4e1fa207f"),
                            Description = "Cotton T-shirt",
                            Image = "tshirt.jpg",
                            Name = "T-shirt",
                            Price = 15
                        },
                        new
                        {
                            Id = new Guid("6cabcd3d-6b87-402b-bc46-06b0fdc88ce2"),
                            CategoryId = new Guid("86a839c3-816a-463b-b639-28c4e1fa207f"),
                            Description = "Denim jeans",
                            Image = "jeans.jpg",
                            Name = "Jeans",
                            Price = 45
                        },
                        new
                        {
                            Id = new Guid("b0d89da0-dd04-4785-9434-f4e6affd985d"),
                            CategoryId = new Guid("86a839c3-816a-463b-b639-28c4e1fa207f"),
                            Description = "Leather jacket",
                            Image = "jacket.jpg",
                            Name = "Jacket",
                            Price = 120
                        },
                        new
                        {
                            Id = new Guid("3b7bd731-5298-4d2d-85e9-0c73fbb4a0ba"),
                            CategoryId = new Guid("778e533a-cd4f-431c-a1f8-96ff9e515ce1"),
                            Description = "High-speed blender",
                            Image = "blender.jpg",
                            Name = "Blender",
                            Price = 85
                        },
                        new
                        {
                            Id = new Guid("0f9ebc47-70ac-41dd-9bd1-acbd9c840315"),
                            CategoryId = new Guid("778e533a-cd4f-431c-a1f8-96ff9e515ce1"),
                            Description = "Comfortable sofa",
                            Image = "couch.jpg",
                            Name = "Couch",
                            Price = 499
                        },
                        new
                        {
                            Id = new Guid("8b54d4f6-8be4-49a2-94df-ae9792495398"),
                            CategoryId = new Guid("778e533a-cd4f-431c-a1f8-96ff9e515ce1"),
                            Description = "Automatic coffee machine",
                            Image = "coffee_maker.jpg",
                            Name = "Coffee Maker",
                            Price = 75
                        },
                        new
                        {
                            Id = new Guid("257c2e58-b4e8-4833-994a-f1bd9b2c5bbd"),
                            CategoryId = new Guid("7eb666f0-9b4d-4c80-a936-104e851f745a"),
                            Description = "Official size basketball",
                            Image = "basketball.jpg",
                            Name = "Basketball",
                            Price = 29
                        },
                        new
                        {
                            Id = new Guid("90f78b07-c0c9-454a-957f-36f7053861f5"),
                            CategoryId = new Guid("7eb666f0-9b4d-4c80-a936-104e851f745a"),
                            Description = "Lightweight racket",
                            Image = "racket.jpg",
                            Name = "Tennis Racket",
                            Price = 99
                        },
                        new
                        {
                            Id = new Guid("a6998d88-2117-4ca8-9414-bfeb90827e37"),
                            CategoryId = new Guid("7eb666f0-9b4d-4c80-a936-104e851f745a"),
                            Description = "High-performance running shoes",
                            Image = "running_shoes.jpg",
                            Name = "Running Shoes",
                            Price = 60
                        },
                        new
                        {
                            Id = new Guid("930090f3-b063-4634-8587-6f9c5c2b8257"),
                            CategoryId = new Guid("96491df2-8f2b-483a-b709-6af695179444"),
                            Description = "Popular action figure",
                            Image = "action_figure.jpg",
                            Name = "Action Figure",
                            Price = 25
                        },
                        new
                        {
                            Id = new Guid("9d0a4e72-e43c-4ea2-82cd-98002e060c32"),
                            CategoryId = new Guid("96491df2-8f2b-483a-b709-6af695179444"),
                            Description = "Remote control car",
                            Image = "toy_car.jpg",
                            Name = "Toy Car",
                            Price = 50
                        },
                        new
                        {
                            Id = new Guid("742765bf-2dda-4c98-9494-1c99a0fd2cd7"),
                            CategoryId = new Guid("96491df2-8f2b-483a-b709-6af695179444"),
                            Description = "Colorful building blocks",
                            Image = "building_blocks.jpg",
                            Name = "Building Blocks",
                            Price = 40
                        },
                        new
                        {
                            Id = new Guid("67188f2e-ec68-407e-bb24-c33deae3fe84"),
                            CategoryId = new Guid("5fa83ce1-299b-4c82-a4c5-99916f7629fd"),
                            Description = "Herbal shampoo",
                            Image = "shampoo.jpg",
                            Name = "Shampoo",
                            Price = 12
                        },
                        new
                        {
                            Id = new Guid("c8e69f1e-7c8f-42e8-ad9b-d06c966b9cfc"),
                            CategoryId = new Guid("5fa83ce1-299b-4c82-a4c5-99916f7629fd"),
                            Description = "Anti-aging cream",
                            Image = "face_cream.jpg",
                            Name = "Face Cream",
                            Price = 35
                        },
                        new
                        {
                            Id = new Guid("69c12b63-74f8-44ec-9d11-62e08e6135ee"),
                            CategoryId = new Guid("5fa83ce1-299b-4c82-a4c5-99916f7629fd"),
                            Description = "Electric toothbrush",
                            Image = "toothbrush.jpg",
                            Name = "Toothbrush",
                            Price = 45
                        },
                        new
                        {
                            Id = new Guid("99300626-a905-4d5a-b88e-8b4583bbce69"),
                            CategoryId = new Guid("7f164413-279c-44a4-9e7c-0967d20aa4d4"),
                            Description = "12V car battery",
                            Image = "car_battery.jpg",
                            Name = "Car Battery",
                            Price = 120
                        },
                        new
                        {
                            Id = new Guid("4309d524-9782-485c-aa66-1e4aaae117c7"),
                            CategoryId = new Guid("7f164413-279c-44a4-9e7c-0967d20aa4d4"),
                            Description = "Leather seat cover",
                            Image = "seat_cover.jpg",
                            Name = "Car Seat Cover",
                            Price = 60
                        },
                        new
                        {
                            Id = new Guid("3b7b3241-abb1-49c5-8dcb-9229d6309f1c"),
                            CategoryId = new Guid("7f164413-279c-44a4-9e7c-0967d20aa4d4"),
                            Description = "Portable tire inflator",
                            Image = "tire_inflator.jpg",
                            Name = "Tire Inflator",
                            Price = 35
                        },
                        new
                        {
                            Id = new Guid("7da246bb-10e2-47f1-bb49-6acf693713d2"),
                            CategoryId = new Guid("eb97dc31-843c-4f28-922d-48520a790717"),
                            Description = "Acoustic guitar",
                            Image = "guitar.jpg",
                            Name = "Guitar",
                            Price = 200
                        },
                        new
                        {
                            Id = new Guid("e19b6dce-cf79-428a-8206-7e3f2cf08b85"),
                            CategoryId = new Guid("eb97dc31-843c-4f28-922d-48520a790717"),
                            Description = "Complete drum kit",
                            Image = "drum_set.jpg",
                            Name = "Drum Set",
                            Price = 550
                        },
                        new
                        {
                            Id = new Guid("8d5eee47-255c-42d7-8dc9-284b0dc4c3da"),
                            CategoryId = new Guid("eb97dc31-843c-4f28-922d-48520a790717"),
                            Description = "Digital piano",
                            Image = "piano.jpg",
                            Name = "Piano",
                            Price = 350
                        },
                        new
                        {
                            Id = new Guid("2d2bf8ca-b244-4688-b696-93c925dcf8e3"),
                            CategoryId = new Guid("d16b79f3-e17e-45b5-a911-0fd3e9818485"),
                            Description = "Heavy-duty stapler",
                            Image = "stapler.jpg",
                            Name = "Stapler",
                            Price = 12
                        },
                        new
                        {
                            Id = new Guid("5d683635-7ead-470a-b696-c9db8d5ccf48"),
                            CategoryId = new Guid("d16b79f3-e17e-45b5-a911-0fd3e9818485"),
                            Description = "Laser printer",
                            Image = "printer.jpg",
                            Name = "Printer",
                            Price = 150
                        },
                        new
                        {
                            Id = new Guid("58ab9b7b-04d6-4928-b323-e227b76cf36e"),
                            CategoryId = new Guid("d16b79f3-e17e-45b5-a911-0fd3e9818485"),
                            Description = "Ergonomic office chair",
                            Image = "desk_chair.jpg",
                            Name = "Desk Chair",
                            Price = 180
                        });
                });

            modelBuilder.Entity("CleanArchitectureCQRs.Domain.Entites.Wishlist", b =>
                {
                    b.Property<Guid>("UsersId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UsersId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("Wishlists");
                });

            modelBuilder.Entity("CleanArchitectureCQRs.Domain.Entites.Product", b =>
                {
                    b.HasOne("CleanArchitectureCQRs.Domain.Entites.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CleanArchitectureCQRs.Domain.Entites.Wishlist", b =>
                {
                    b.HasOne("CleanArchitectureCQRs.Domain.Entites.Product", "Product")
                        .WithMany("Wishlists")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CleanArchitectureCQRs.Domain.Entites.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("CleanArchitectureCQRs.Domain.Entites.Product", b =>
                {
                    b.Navigation("Wishlists");
                });
#pragma warning restore 612, 618
        }
    }
}
