// <auto-generated />
using System;
using CleanArchitectureCQRs.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CleanArchitectureCQRs.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CleanArchitectureCQRs.Domain.Entites.Category", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("categories", (string)null);

                    b.HasData(
                        new
                        {
                            CategoryId = new Guid("db72e407-4864-4ce0-8115-3eede4e44420"),
                            CategoryName = "Electronics",
                            Description = "Devices and gadgets"
                        },
                        new
                        {
                            CategoryId = new Guid("e1fc458c-cbe4-4697-869e-24cad9c40cb4"),
                            CategoryName = "Books",
                            Description = "Various genres of books"
                        },
                        new
                        {
                            CategoryId = new Guid("2dd03caa-bd6e-4cfe-b399-101fe234751a"),
                            CategoryName = "Clothing",
                            Description = "Apparel for men and women"
                        },
                        new
                        {
                            CategoryId = new Guid("2711ad5b-7850-4987-a4d5-a0db63eb6ba9"),
                            CategoryName = "Home & Kitchen",
                            Description = "Household items"
                        },
                        new
                        {
                            CategoryId = new Guid("2d71b722-2683-4f22-b76f-47b65215862a"),
                            CategoryName = "Sports",
                            Description = "Sporting goods and equipment"
                        },
                        new
                        {
                            CategoryId = new Guid("47605a6e-c86f-4280-bc88-819f7761eed7"),
                            CategoryName = "Toys",
                            Description = "Toys for children of all ages"
                        },
                        new
                        {
                            CategoryId = new Guid("16c88735-51ab-4a32-b1fb-36c2ede09b3a"),
                            CategoryName = "Health & Beauty",
                            Description = "Healthcare and beauty products"
                        },
                        new
                        {
                            CategoryId = new Guid("7b3a315a-8b3c-4ab8-b3e5-17d138a40340"),
                            CategoryName = "Automotive",
                            Description = "Car parts and accessories"
                        },
                        new
                        {
                            CategoryId = new Guid("331663d3-75df-487c-8ef0-00ec96782af2"),
                            CategoryName = "Music",
                            Description = "Instruments and music equipment"
                        },
                        new
                        {
                            CategoryId = new Guid("04c4ffe2-4d94-487e-b889-0caaebb771e1"),
                            CategoryName = "Office Supplies",
                            Description = "Stationery and office essentials"
                        });
                });

            modelBuilder.Entity("CleanArchitectureCQRs.Domain.Entites.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("products", (string)null);

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("27026ad2-227d-4565-bb9a-a73617ef4aaf"),
                            CategoryId = new Guid("db72e407-4864-4ce0-8115-3eede4e44420"),
                            Description = "Latest model",
                            Image = "smartphone.jpg",
                            Name = "Smartphone",
                            Price = 699
                        },
                        new
                        {
                            ProductId = new Guid("79a1f31d-1d71-42ea-b40b-56f9d6378246"),
                            CategoryId = new Guid("db72e407-4864-4ce0-8115-3eede4e44420"),
                            Description = "15-inch display",
                            Image = "laptop.jpg",
                            Name = "Laptop",
                            Price = 999
                        },
                        new
                        {
                            ProductId = new Guid("39865d58-f2dc-4b85-93ae-2f9a178a395b"),
                            CategoryId = new Guid("db72e407-4864-4ce0-8115-3eede4e44420"),
                            Description = "Water-resistant smartwatch",
                            Image = "smartwatch.jpg",
                            Name = "Smartwatch",
                            Price = 199
                        },
                        new
                        {
                            ProductId = new Guid("7df2e22a-d643-463e-bf3b-af3aa0e5b1dc"),
                            CategoryId = new Guid("e1fc458c-cbe4-4697-869e-24cad9c40cb4"),
                            Description = "Portable e-book reader",
                            Image = "ebook.jpg",
                            Name = "E-book Reader",
                            Price = 129
                        },
                        new
                        {
                            ProductId = new Guid("dc866dd1-6d16-4870-b4ad-3d7a7a7d0777"),
                            CategoryId = new Guid("e1fc458c-cbe4-4697-869e-24cad9c40cb4"),
                            Description = "Bestselling novel",
                            Image = "book.jpg",
                            Name = "Fiction Book",
                            Price = 20
                        },
                        new
                        {
                            ProductId = new Guid("e6ea9f17-ac41-4ad0-8c86-942831accfad"),
                            CategoryId = new Guid("e1fc458c-cbe4-4697-869e-24cad9c40cb4"),
                            Description = "Self-improvement guide",
                            Image = "self_help.jpg",
                            Name = "Self-help Book",
                            Price = 15
                        },
                        new
                        {
                            ProductId = new Guid("c87d4738-0453-4021-94b9-8d3a0db61fa1"),
                            CategoryId = new Guid("2dd03caa-bd6e-4cfe-b399-101fe234751a"),
                            Description = "Cotton T-shirt",
                            Image = "tshirt.jpg",
                            Name = "T-shirt",
                            Price = 15
                        },
                        new
                        {
                            ProductId = new Guid("8c17c175-ff51-4ae9-943c-2343f1405b90"),
                            CategoryId = new Guid("2dd03caa-bd6e-4cfe-b399-101fe234751a"),
                            Description = "Denim jeans",
                            Image = "jeans.jpg",
                            Name = "Jeans",
                            Price = 45
                        },
                        new
                        {
                            ProductId = new Guid("4a94cff0-0b2f-4013-8ea3-2dac82543093"),
                            CategoryId = new Guid("2dd03caa-bd6e-4cfe-b399-101fe234751a"),
                            Description = "Leather jacket",
                            Image = "jacket.jpg",
                            Name = "Jacket",
                            Price = 120
                        },
                        new
                        {
                            ProductId = new Guid("4f73ae5a-0b04-472c-94aa-13189edf21fc"),
                            CategoryId = new Guid("2711ad5b-7850-4987-a4d5-a0db63eb6ba9"),
                            Description = "High-speed blender",
                            Image = "blender.jpg",
                            Name = "Blender",
                            Price = 85
                        },
                        new
                        {
                            ProductId = new Guid("405e8e1a-07f8-4cc1-9ed8-646e8d893624"),
                            CategoryId = new Guid("2711ad5b-7850-4987-a4d5-a0db63eb6ba9"),
                            Description = "Comfortable sofa",
                            Image = "couch.jpg",
                            Name = "Couch",
                            Price = 499
                        },
                        new
                        {
                            ProductId = new Guid("8cb4a577-86c4-4d21-b8fa-51feecb1a080"),
                            CategoryId = new Guid("2711ad5b-7850-4987-a4d5-a0db63eb6ba9"),
                            Description = "Automatic coffee machine",
                            Image = "coffee_maker.jpg",
                            Name = "Coffee Maker",
                            Price = 75
                        },
                        new
                        {
                            ProductId = new Guid("e2958444-5a96-4124-bc5e-53e9cf094f4b"),
                            CategoryId = new Guid("2d71b722-2683-4f22-b76f-47b65215862a"),
                            Description = "Official size basketball",
                            Image = "basketball.jpg",
                            Name = "Basketball",
                            Price = 29
                        },
                        new
                        {
                            ProductId = new Guid("e07078a5-0ce1-4f8d-9ab4-c4abfb104e37"),
                            CategoryId = new Guid("2d71b722-2683-4f22-b76f-47b65215862a"),
                            Description = "Lightweight racket",
                            Image = "racket.jpg",
                            Name = "Tennis Racket",
                            Price = 99
                        },
                        new
                        {
                            ProductId = new Guid("6bdf8817-e7da-4ce7-b94a-2fec19e4e085"),
                            CategoryId = new Guid("2d71b722-2683-4f22-b76f-47b65215862a"),
                            Description = "High-performance running shoes",
                            Image = "running_shoes.jpg",
                            Name = "Running Shoes",
                            Price = 60
                        },
                        new
                        {
                            ProductId = new Guid("0a27982e-34db-4c8c-9cd4-17678824da1e"),
                            CategoryId = new Guid("47605a6e-c86f-4280-bc88-819f7761eed7"),
                            Description = "Popular action figure",
                            Image = "action_figure.jpg",
                            Name = "Action Figure",
                            Price = 25
                        },
                        new
                        {
                            ProductId = new Guid("3018f70e-d15e-4c69-89ae-a3c3dc5c2782"),
                            CategoryId = new Guid("47605a6e-c86f-4280-bc88-819f7761eed7"),
                            Description = "Remote control car",
                            Image = "toy_car.jpg",
                            Name = "Toy Car",
                            Price = 50
                        },
                        new
                        {
                            ProductId = new Guid("b737837c-e328-435a-8bf1-c002eec9e4c8"),
                            CategoryId = new Guid("47605a6e-c86f-4280-bc88-819f7761eed7"),
                            Description = "Colorful building blocks",
                            Image = "building_blocks.jpg",
                            Name = "Building Blocks",
                            Price = 40
                        },
                        new
                        {
                            ProductId = new Guid("05b2bded-9c50-4c9d-9157-8acdec29e4dd"),
                            CategoryId = new Guid("16c88735-51ab-4a32-b1fb-36c2ede09b3a"),
                            Description = "Herbal shampoo",
                            Image = "shampoo.jpg",
                            Name = "Shampoo",
                            Price = 12
                        },
                        new
                        {
                            ProductId = new Guid("7ec02090-e500-4115-996b-fa70c656e003"),
                            CategoryId = new Guid("16c88735-51ab-4a32-b1fb-36c2ede09b3a"),
                            Description = "Anti-aging cream",
                            Image = "face_cream.jpg",
                            Name = "Face Cream",
                            Price = 35
                        },
                        new
                        {
                            ProductId = new Guid("4790871f-e5a1-48f8-a3ae-5d9a02ac8878"),
                            CategoryId = new Guid("16c88735-51ab-4a32-b1fb-36c2ede09b3a"),
                            Description = "Electric toothbrush",
                            Image = "toothbrush.jpg",
                            Name = "Toothbrush",
                            Price = 45
                        },
                        new
                        {
                            ProductId = new Guid("cc51d424-c008-4334-8e72-a432e12985e8"),
                            CategoryId = new Guid("7b3a315a-8b3c-4ab8-b3e5-17d138a40340"),
                            Description = "12V car battery",
                            Image = "car_battery.jpg",
                            Name = "Car Battery",
                            Price = 120
                        },
                        new
                        {
                            ProductId = new Guid("61a12273-71ac-425b-95e4-44f2fc874900"),
                            CategoryId = new Guid("7b3a315a-8b3c-4ab8-b3e5-17d138a40340"),
                            Description = "Leather seat cover",
                            Image = "seat_cover.jpg",
                            Name = "Car Seat Cover",
                            Price = 60
                        },
                        new
                        {
                            ProductId = new Guid("74ed12b5-11c2-45e8-97fc-14deee57aa7b"),
                            CategoryId = new Guid("7b3a315a-8b3c-4ab8-b3e5-17d138a40340"),
                            Description = "Portable tire inflator",
                            Image = "tire_inflator.jpg",
                            Name = "Tire Inflator",
                            Price = 35
                        },
                        new
                        {
                            ProductId = new Guid("1c465a17-a117-4ea7-b2a6-bf3e3a8123db"),
                            CategoryId = new Guid("331663d3-75df-487c-8ef0-00ec96782af2"),
                            Description = "Acoustic guitar",
                            Image = "guitar.jpg",
                            Name = "Guitar",
                            Price = 200
                        },
                        new
                        {
                            ProductId = new Guid("a8113b83-4a2a-4b8c-9cb1-e5d49b1c783b"),
                            CategoryId = new Guid("331663d3-75df-487c-8ef0-00ec96782af2"),
                            Description = "Complete drum kit",
                            Image = "drum_set.jpg",
                            Name = "Drum Set",
                            Price = 550
                        },
                        new
                        {
                            ProductId = new Guid("9c916fbb-8b45-4881-82ef-bc474772eaa0"),
                            CategoryId = new Guid("331663d3-75df-487c-8ef0-00ec96782af2"),
                            Description = "Digital piano",
                            Image = "piano.jpg",
                            Name = "Piano",
                            Price = 350
                        },
                        new
                        {
                            ProductId = new Guid("52cf97cd-5d44-437e-8714-9f5034f4878e"),
                            CategoryId = new Guid("04c4ffe2-4d94-487e-b889-0caaebb771e1"),
                            Description = "Heavy-duty stapler",
                            Image = "stapler.jpg",
                            Name = "Stapler",
                            Price = 12
                        },
                        new
                        {
                            ProductId = new Guid("a74ca1f3-8a60-421d-a685-d7bfec237921"),
                            CategoryId = new Guid("04c4ffe2-4d94-487e-b889-0caaebb771e1"),
                            Description = "Laser printer",
                            Image = "printer.jpg",
                            Name = "Printer",
                            Price = 150
                        },
                        new
                        {
                            ProductId = new Guid("91c219c3-c300-4fc1-800b-ac1ccc4fa0e9"),
                            CategoryId = new Guid("04c4ffe2-4d94-487e-b889-0caaebb771e1"),
                            Description = "Ergonomic office chair",
                            Image = "desk_chair.jpg",
                            Name = "Desk Chair",
                            Price = 180
                        });
                });

            modelBuilder.Entity("CleanArchitectureCQRs.Domain.Entites.Wishlist", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ProductId", "UsersId");

                    b.ToTable("wishLists", (string)null);
                });

            modelBuilder.Entity("CleanArchitectureCQRs.Domain.Entites.Product", b =>
                {
                    b.HasOne("CleanArchitectureCQRs.Domain.Entites.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CleanArchitectureCQRs.Domain.Entites.Wishlist", b =>
                {
                    b.HasOne("CleanArchitectureCQRs.Domain.Entites.Product", "Product")
                        .WithMany("Wishlist")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CleanArchitectureCQRs.Domain.Entites.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("CleanArchitectureCQRs.Domain.Entites.Product", b =>
                {
                    b.Navigation("Wishlist");
                });
#pragma warning restore 612, 618
        }
    }
}
